name: Mypy Type Check

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Mypy
      run: |
        python -m pip install --upgrade pip
        pip install Mypy

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Run Mypy
      run: |
        cd ./app
        mypy app.py